---
- name: Hello Events
  hosts: localhost
  sources:
      - name: range
        ansible.eda.range:
          limit: 5
  rules:
    - name: multiple conditions
      condition:
        all:
          - event.i == 1
          - event.i == 2
          - event.i == events.m.i + 3
      action:
        debug:
          msg:
            - "first: {{ events.m_0 }}"
            - "second: {{ events.m_1 }}"
            - "third: {{ events }}"
