---
- name: RuleSet1
  hosts: localhost
  sources:
      - name: range
        ansible.eda.range:
          limit: 5
  rules:
    - name: R1
      condition:
        all:
          - events.first << event.i == 0
          - events.second << event.i == 1
          - events.third << event.i == events.first.i + 2
      action:
        post_event:
          ruleset: RuleSet2
          event:
            sample_post_data: "{{events.third}}"
- name: RuleSet2
  hosts: localhost
  sources:
      - name: range
        ansible.eda.range:
          limit: 5
  rules:
    - name: R2
      condition:
        all:
          - events.sample_post_data.i == 2
      action:
        print_event:
          pretty: true
