---
- name: Hello Events
  hosts: localhost
  sources:
    - name: range
      ansible.eda.range:
        limit: 5
  rules:
    - name: Say Hello
      # enabled: false
      condition: event.i > 0
      action:
        run_playbook:
          name: ansible.eda.hello