---
- name: Hello Events
  hosts: localhost
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: Say Hello
      condition: event.i > 0
      action:
        debug:
        # run_playbook:
        #   name: ansible.eda.hello