---
- name: Listen for events on a webhook
  hosts: localhost
  ## Define our source for events
  sources:
    - name: Webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  ## Define the conditions we are looking for
  rules:

    - name: Launch Fix
      condition: event.payload.alert == "Example problem" and event.payload.status == "Firing"
      action:
        run_job_template:
          name: 'Fix example problem'
          organization: Default
