---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - name: Webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  ## Define the conditions we are looking for
  rules:

    - name: Debug if non empty
      condition: true
      action:
        debug:
