---
- name: Auto remediate high CPU usage
  hosts: "{{ ansible_eda.event.payload.host | default('localhost') }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Gather top CPU processes
      ansible.builtin.shell: "ps -eo pid,comm,%cpu --sort=-%cpu"
      register: process_info

    - name: Display process info
      ansible.builtin.debug:
        var: process_info.stdout_lines

    - name: Kill stress-ng process if high CPU
      ansible.builtin.shell: "pkill stress-ng"
      when: "'stress-ng' in process_info.stdout"
      ignore_errors: true
      # ignore_errors is a good practice here in case stress-ng isn't running.

    - name: Restart httpd if high CPU
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: "'httpd' in process_info.stdout"
